// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpb490i1yjbyU_wjRpnI1ZvXqrpElihoQ',
    appId: '1:572788156389:web:8aecabc1dd10c05b7e710c',
    messagingSenderId: '572788156389',
    projectId: 'personal-finance-app-5ac3f',
    authDomain: 'personal-finance-app-5ac3f.firebaseapp.com',
    storageBucket: 'personal-finance-app-5ac3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ9iQ0FUf6OsHkKN0Y-0hdbzWsQA51Qrw',
    appId: '1:572788156389:android:5c2ed3b098bb307d7e710c',
    messagingSenderId: '572788156389',
    projectId: 'personal-finance-app-5ac3f',
    storageBucket: 'personal-finance-app-5ac3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvLJaTz9wuONVr1Urm6BEye0BrRJJ757o',
    appId: '1:572788156389:ios:2659dcda496fa3707e710c',
    messagingSenderId: '572788156389',
    projectId: 'personal-finance-app-5ac3f',
    storageBucket: 'personal-finance-app-5ac3f.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvLJaTz9wuONVr1Urm6BEye0BrRJJ757o',
    appId: '1:572788156389:ios:2659dcda496fa3707e710c',
    messagingSenderId: '572788156389',
    projectId: 'personal-finance-app-5ac3f',
    storageBucket: 'personal-finance-app-5ac3f.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpb490i1yjbyU_wjRpnI1ZvXqrpElihoQ',
    appId: '1:572788156389:web:847cd428c85666067e710c',
    messagingSenderId: '572788156389',
    projectId: 'personal-finance-app-5ac3f',
    authDomain: 'personal-finance-app-5ac3f.firebaseapp.com',
    storageBucket: 'personal-finance-app-5ac3f.firebasestorage.app',
  );
}
