import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:personal_finance_app_flutter/core/app_theme.dart';
import 'package:personal_finance_app_flutter/routes.dart';
import 'package:personal_finance_app_flutter/screens/auth_wrapper.dart';
import 'firebase_options.dart'; // This file is generated by flutterfire

Future<void> main() async {
  // Ensure Flutter widgets are initialized
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Run the app
  runApp(const PersonalFinanceApp());
}

class PersonalFinanceApp extends StatelessWidget {
  const PersonalFinanceApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Personal Finance Management',
      theme: AppTheme.lightTheme,
      debugShowCheckedModeBanner: false,
      // The AuthWrapper will decide which screen to show
      home: const AuthWrapper(),
      // We still use onGenerateRoute for all other in-app navigation
      onGenerateRoute: AppRoutes.generateRoute,
    );
  }
}